language: python
python:
  - "3.4"

install: "pip install -r requirements.txt"

services:
  postgresql

before_script:
  - psql -c "create user apye with password 'iDDLpkP1uv' " -U postgres
  - psql -c "create database apye;" -U postgres
  - psql -c "grant all privileges on database apye to apye;" -U postgres
  - python manage.py db upgrade

script: python test_base.py

