language: python
python:
  - "3.4"

install: "pip install -r requirements.txt"

services:
  postgresql

before_script:
  - psql -c 'create database APYE_USERS;' -U postgres

script: python test_base.py

env:
  - APP_SETTINGS=config.TestConfiguration
  - SECRET_KEY=Sql1D00WTF.
  - DATABASE_URL="postgresql://postgres:@localhost/APYE_USERS"

