---
- hosts: all
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt: upgrade=yes update_cache=yes cache_valid_time=3600

    - name: Install basic dependencies
      apt: pkg={{ item }} state=present
      with_items:
        - build-essential
        - git
        - python3.4-dev
        - libpq-dev
        - postgresql

    - block:
      - name: Download get-pip.py
        get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp

      - name: Install pip
        command: "python3.4 /tmp/get-pip.py"
...
