"""empty message

Revision ID: 8e172fa2c4b7
Revises: 6b4a53a7bdcc
Create Date: 2016-11-11 01:15:12.628975

"""

# revision identifiers, used by Alembic.
revision = '8e172fa2c4b7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=20), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('authenticated', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
