"""empty message

Revision ID: ca6bc75b67a3
Revises: 957f266797b8
Create Date: 2016-11-06 15:55:24.416706

"""

# revision identifiers, used by Alembic.
revision = 'ca6bc75b67a3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=20), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('authenticated', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
