"""empty message

Revision ID: f6e1c8fcd6e0
Revises: ca6bc75b67a3
Create Date: 2016-11-06 15:56:52.232747

"""

# revision identifiers, used by Alembic.
revision = 'f6e1c8fcd6e0'
down_revision = 'ca6bc75b67a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
